export const siteConfig = {
  name: "Summit Home Remodeling",
  tagline: "Northwest Arkansas' Premier Home Remodeling Contractor",
  description:
    "Summit Home Remodeling transforms homes in Rogers, AR and surrounding Northwest Arkansas communities. Kitchens, bathrooms, additions, and basement finishes — built to last, designed to impress.",
  url: "https://summithomeremodeling.com",
  phone: "(479) 319-4200",
  phoneRaw: "+14793194200",
  email: "hello@summithomeremodeling.com",
  address: {
    street: "1247 W Commerce St",
    city: "Rogers",
    state: "AR",
    zip: "72756",
    full: "1247 W Commerce St, Rogers, AR 72756",
  },
  geo: {
    lat: 36.332,
    lng: -94.1185,
  },
  license: "AR Contractor License #CR-2011-0847",
  established: 2011,
  hours: {
    weekday: "Mon–Fri: 8:00 AM – 6:00 PM",
    saturday: "Sat: 9:00 AM – 4:00 PM",
    sunday: "Sun: Closed",
  },
  social: {
    facebook: "https://facebook.com/summithomeremodeling",
    instagram: "https://instagram.com/summithomeremodeling",
    houzz: "https://houzz.com/pro/summithomeremodeling",
    google: "https://g.page/summithomeremodeling",
  },
  stats: {
    yearsInBusiness: 15,
    projectsCompleted: 430,
    rating: 4.9,
    reviews: 127,
    warrantyYears: 5,
  },
  services: [
    {
      slug: "kitchen-remodeling",
      name: "Kitchen Remodeling",
      shortDesc: "Custom kitchens that become the heart of your home.",
      icon: "🍳",
      priceRange: "$25,000 – $85,000",
    },
    {
      slug: "bathroom-remodeling",
      name: "Bathroom Remodeling",
      shortDesc: "Spa-quality bathrooms tailored to your lifestyle.",
      icon: "🛁",
      priceRange: "$12,000 – $55,000",
    },
    {
      slug: "home-additions",
      name: "Home Additions",
      shortDesc: "Expand your space without leaving the neighborhood you love.",
      icon: "🏠",
      priceRange: "$60,000 – $250,000+",
    },
    {
      slug: "basement-finishing",
      name: "Basement Finishing",
      shortDesc: "Turn wasted square footage into living space.",
      icon: "🎬",
      priceRange: "$30,000 – $90,000",
    },
  ],
  serviceAreas: [
    {
      slug: "rogers",
      city: "Rogers",
      state: "AR",
      zip: "72756",
      distanceMiles: 0,
      distance: "Home office",
      geo: { lat: 36.332, lng: -94.1185 },
      isPrimary: true,
    },
    {
      slug: "bentonville",
      city: "Bentonville",
      state: "AR",
      zip: "72712",
      distanceMiles: 8,
      distance: "8 mi",
      geo: { lat: 36.3729, lng: -94.2088 },
      isPrimary: false,
    },
    {
      slug: "lowell",
      city: "Lowell",
      state: "AR",
      zip: "72745",
      distanceMiles: 5,
      distance: "5 mi",
      geo: { lat: 36.2548, lng: -94.1346 },
      isPrimary: false,
    },
    {
      slug: "cave-springs",
      city: "Cave Springs",
      state: "AR",
      zip: "72718",
      distanceMiles: 6,
      distance: "6 mi",
      geo: { lat: 36.3831, lng: -94.2338 },
      isPrimary: false,
    },
    {
      slug: "springdale",
      city: "Springdale",
      state: "AR",
      zip: "72764",
      distanceMiles: 12,
      distance: "12 mi",
      geo: { lat: 36.1867, lng: -94.1288 },
      isPrimary: false,
    },
    {
      slug: "fayetteville",
      city: "Fayetteville",
      state: "AR",
      zip: "72701",
      distanceMiles: 18,
      distance: "18 mi",
      geo: { lat: 36.0626, lng: -94.1574 },
      isPrimary: false,
    },
  ],
};

export type ServiceArea = (typeof siteConfig.serviceAreas)[number];
export type Service = (typeof siteConfig.services)[number];
